version: 2.1
workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          context: falco
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  test:
    docker:
      - image: docker.io/golang:1.17.5
    steps:
      - checkout
      - run:
          name: Test
          command: make test
  release:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: Prepare env
          command: |
            echo ${DOCKERHUB_SECRET} | docker login -u ${DOCKERHUB_USER} --password-stdin
      - run:
          name: Install goreleaser
          command: |
            echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
            sudo apt update
            sudo apt install goreleaser

      - run:
          name: Run goreleaser
          command: goreleaser
